# NumPy A to Z — The Complete Reference Notebook (Explained Simply)

This notebook explains NumPy from the very beginning to the advanced parts,
using plain, everyday language and simple examples like numbers, marks,
fruits, and temperatures. No jargon is left unexplained — every function
and every attribute is described in easy words before it is used in code.

**How to read this notebook**

Read the text above each code cell first. It tells you, in simple words,
what the code is about to do and why it matters. Then run the code and
look at the output. Everything here runs on its own — no external files
are needed.

**Table of Contents**

1. Core Concepts and Array Basics
2. Accessing and Manipulating Data
3. Structural and Shape Transformations
4. Mathematical Operations and Vectorization
5. Advanced and Specialized Modules
6. Performance Optimization
7. Quick Reference Cheat-Sheet


In [43]:
import numpy as np

# This line just tells us which version of NumPy we have installed.
print("NumPy version:", np.__version__)

NumPy version: 2.1.3


## 1. Core Concepts and Array Basics

### What is NumPy?

NumPy is a Python tool/library for working with lists of numbers, but much faster
and much more powerful than a normal Python list. Think of a normal
Python list as a row of boxes where each box can hold anything — a
number, a word, even another list. A NumPy array is more like a row of
identical drawers, all built to hold the same type of item (for example,
all whole numbers, or all decimal numbers). Because every drawer is the
same size and type, NumPy can read and process them extremely fast.

### The `ndarray` object — what makes it different from a Python list?

`ndarray` stands for "N-dimensional array". It is the basic object that
NumPy is built around. Here is why it behaves differently from a normal
Python list:

- **Same type inside (homogeneous):** every value inside a NumPy array
  must be of the same data type (all integers, or all decimals, for
  example). A Python list can freely mix a number, a word, and a list
  together — a NumPy array cannot.
- **Stored next to each other in memory (contiguous memory):** imagine a
  row of lockers placed right next to each other, versus lockers
  scattered randomly around a building. NumPy stores its numbers like the
  first case — right next to each other — which is a big reason why it is
  so fast. A Python list is more like the scattered lockers: each item is
  actually stored somewhere else in memory, and the list only holds
  pointers (addresses) to where they live.
- **Fixed size operations run in fast, compiled code:** because of the
  two points above, NumPy can hand off the heavy number-crunching to
  code written in C (a much faster language than Python), instead of
  going through Python's slower step-by-step loop.


In [44]:
# A simple Python list — can hold mixed types, and is slower for maths
python_list = [1, 2, 3, 4, 5]

# The same numbers as a NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])

print("Python list:", python_list)
print("NumPy array:", numpy_array)
print("Type of numpy_array:", type(numpy_array))

Python list: [1, 2, 3, 4, 5]
NumPy array: [1 2 3 4 5]
Type of numpy_array: <class 'numpy.ndarray'>


In [45]:
# Why this matters: adding a number to every item.
# With a plain Python list, '+' does NOT add to every item — it just
# joins ("concatenates") two lists together.
try:
    python_list + 10
except TypeError as error:
    print("Python list error:", error)

# With a NumPy array, '+' adds 10 to EVERY number at once. This is called
# a "vectorized" operation, and we will explain it fully in Section 4.
print("NumPy array + 10:", numpy_array + 10)

Python list error: can only concatenate list (not "int") to list
NumPy array + 10: [11 12 13 14 15]


### Array attributes — checking the "shape" of your data

An "attribute" is just a small piece of information that an array already
knows about itself. You don't need to calculate it — you just ask for it.
Below are the four attributes you will use constantly:

- `.shape` — tells you how many rows and columns (and any deeper
  dimensions) the array has. Think of it as the array's size, written as
  (rows, columns).
- `.ndim` — tells you how many dimensions the array has. A plain list of
  numbers is 1 dimension. A table of numbers (rows and columns) is 2
  dimensions. A stack of tables is 3 dimensions.
- `.size` — tells you the TOTAL number of individual values in the array,
  no matter how many dimensions it has.
- `.dtype` — tells you what type of data is stored inside (for example,
  whole numbers or decimal numbers).


In [46]:
# A simple 1-dimensional array — just a single row of numbers
marks_1d = np.array([85, 90, 78, 92])

print("Shape:", marks_1d.shape)   # (4,) means 4 items in a single row
print("Dimensions:", marks_1d.ndim)   # 1 dimension
print("Total items:", marks_1d.size)   # 4 items in total
print("Data type:", marks_1d.dtype)   # what kind of numbers are stored

Shape: (4,)
Dimensions: 1
Total items: 4
Data type: int64


In [47]:
# A 2-dimensional array — like a small table.
# Imagine 3 students, each with 2 subject marks (Math, Science).
marks_2d = np.array([
    [85, 90],   # student 1: Math=85, Science=90
    [78, 88],   # student 2
    [92, 95]    # student 3
])

print("Shape:", marks_2d.shape)   # (3, 2) -> 3 rows, 2 columns
print("Dimensions:", marks_2d.ndim)   # 2 dimensions (rows and columns)
print("Total items:", marks_2d.size)   # 3 x 2 = 6 items in total
print("Data type:", marks_2d.dtype)

Shape: (3, 2)
Dimensions: 2
Total items: 6
Data type: int64


### Array creation functions — the easy ways to build an array

You will rarely type out every number by hand. NumPy gives you shortcut
functions to build arrays quickly:

- `np.array()` — turns a normal Python list (or list of lists) into a
  NumPy array. This is the most basic way to create one.
- `np.zeros()` — builds an array completely filled with the number 0.
  Useful when you want an empty "placeholder" array of a certain size
  that you will fill in later.
- `np.ones()` — builds an array completely filled with the number 1.
- `np.arange()` — builds an array of numbers that count up (or down) by a
  fixed step, similar to Python's built-in `range()`, but it returns a
  real NumPy array.
- `np.linspace()` — builds an array of a chosen number of evenly-spaced
  values between a start point and an end point. You choose HOW MANY
  numbers you want, and NumPy spaces them out evenly for you.


In [48]:
# np.array() — from a plain Python list
a = np.array([10, 20, 30])
print("np.array():", a)

np.array(): [10 20 30]


In [49]:
# np.zeros() — a 2x3 array of all zeros (2 rows, 3 columns)
zeros_array = np.zeros((2, 3))
print("np.zeros((2, 3)):\n", zeros_array)

np.zeros((2, 3)):
 [[0. 0. 0.]
 [0. 0. 0.]]


In [50]:
# np.ones() — a 3x2 array of all ones
ones_array = np.ones((3, 2))
print("np.ones((3, 2)):\n", ones_array)

np.ones((3, 2)):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [51]:
# np.arange(start, stop, step) — counts up from 'start' to just before 'stop'
counting = np.arange(0, 10, 2)   # start at 0, stop before 10, step by 2
print("np.arange(0, 10, 2):", counting)

np.arange(0, 10, 2): [0 2 4 6 8]


In [52]:
# np.linspace(start, stop, how_many) — picks an exact NUMBER of evenly spread values
# Here we ask for 5 values spread evenly between 0 and 1 (both included).
spread_out = np.linspace(0, 1, 5)
print("np.linspace(0, 1, 5):", spread_out)

np.linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


### Data types (`dtype`) — telling NumPy exactly how to store your numbers

Every NumPy array stores its numbers using a specific "data type", or
`dtype` for short. This matters for two reasons: how much computer memory
it uses, and how precise the numbers are.

- `np.int64` — a whole number (no decimal point) stored using 64 bits of
  memory. Bigger bit-size means it can store bigger numbers, but uses
  more memory.
- `np.float32` — a decimal number stored using 32 bits of memory. This
  uses less memory than the default (`float64`), which matters a lot
  when you are working with millions of numbers, such as in machine
  learning.
- `.astype()` — a method that converts an array from one data type into
  another. For example, turning decimal numbers into whole numbers.


In [53]:
# Choosing a data type when creating an array
whole_numbers = np.array([1, 2, 3], dtype=np.int64)
decimal_numbers = np.array([1.5, 2.5, 3.5], dtype=np.float32)

print("Whole numbers:", whole_numbers, "-> dtype:", whole_numbers.dtype)
print("Decimal numbers:", decimal_numbers, "-> dtype:", decimal_numbers.dtype)

Whole numbers: [1 2 3] -> dtype: int64
Decimal numbers: [1.5 2.5 3.5] -> dtype: float32


In [54]:
# .astype() — converting one data type into another AFTER the array already exists
prices = np.array([19.99, 5.50, 100.25])
print("Original (decimal):", prices, prices.dtype)

# Converting decimals into whole numbers. Notice this CUTS OFF the decimal part,
# it does not round to the nearest whole number.
whole_prices = prices.astype(np.int64)
print("Converted (whole numbers):", whole_prices, whole_prices.dtype)

Original (decimal): [ 19.99   5.5  100.25] float64
Converted (whole numbers): [ 19   5 100] int64


## 2. Accessing and Manipulating Data

Once you have an array, the next most common task is picking out the
specific parts of it that you need. This section covers the different
ways to do that.

### Indexing and slicing — picking out specific values

"Indexing" means picking out ONE single value using its position number.
"Slicing" means picking out a RANGE of values at once. In both Python and
NumPy, counting positions always starts at 0, not 1.


In [55]:
# A simple 1-dimensional array of temperatures recorded over a week (in Celsius)
temperatures = np.array([21, 23, 19, 25, 22, 24, 20])
#                index:   0   1   2   3   4   5   6

# Indexing: picking ONE value by its position
print("First day's temperature:", temperatures[0])
print("Third day's temperature:", temperatures[2])
print("Last day's temperature (using -1):", temperatures[-1])

First day's temperature: 21
Third day's temperature: 19
Last day's temperature (using -1): 20


In [56]:
# Slicing: picking a RANGE of values, written as array[start:stop]
# The 'stop' position is NOT included in the result.
print("First 3 days:", temperatures[0:3])
print("Days 3 to 5:", temperatures[2:5])
print("Every other day:", temperatures[::2])

First 3 days: [21 23 19]
Days 3 to 5: [19 25 22]
Every other day: [21 19 22 20]


### Indexing and slicing in 2 dimensions

For a table-like (2D) array, you give two positions: the row position
first, and the column position second, written as `array[row, column]`.


In [57]:
# A small table: 3 students, each with 2 subject marks (Math, Science)
marks = np.array([
    [85, 90],
    [78, 88],
    [92, 95]
])

print("Student at row 0, column 1 (Math student's Science mark):", marks[0, 1])
print("Whole first row (all of student 1's marks):", marks[0])
print("Whole first column (everyone's Math marks):", marks[:, 0])

Student at row 0, column 1 (Math student's Science mark): 90
Whole first row (all of student 1's marks): [85 90]
Whole first column (everyone's Math marks): [85 78 92]


In [58]:
# Slicing a 2D array: array[row_start:row_stop, col_start:col_stop]
# Example: first 2 students, both subjects
print(marks[0:2, 0:2])

[[85 90]
 [78 88]]


### Advanced (fancy) indexing — picking out scattered, non-consecutive items

Sometimes you don't want a straight range of items — you want specific
positions that are scattered around, such as item 0, then item 3, then
item 7. "Fancy indexing" means you give NumPy a LIST of positions instead
of a single start/stop range, and it collects exactly those items for
you.


In [59]:
grades = np.array([60, 75, 80, 55, 90, 65, 100])

# Passing a LIST of positions we want, in any order we like
wanted_positions = [0, 2, 4]
print("Grades at positions 0, 2, and 4:", grades[wanted_positions])

# We can even repeat a position or change the order
print("Custom order:", grades[[4, 0, 0, 6]])

Grades at positions 0, 2, and 4: [60 80 90]
Custom order: [ 90  60  60 100]


### Boolean masking / filtering — picking out items that match a condition

A "boolean mask" is a list of `True`/`False` values, the same length as
your array, where `True` means "keep this item" and `False` means "throw
this item away". NumPy lets you build this mask directly from a
condition, such as "is this number bigger than 5?", and then use it to
filter the array in one step.


In [60]:
scores = np.array([45, 82, 91, 34, 67, 88, 20])

# Step 1: build the True/False mask using a condition
passing_mask = scores >= 50
print("Mask (True = passing):", passing_mask)

# Step 2: use the mask to keep only the matching values
passing_scores = scores[passing_mask]
print("Passing scores only:", passing_scores)

# You can also do it in one line, which is the most common style
print("One line version:", scores[scores >= 50])

Mask (True = passing): [False  True  True False  True  True False]
Passing scores only: [82 91 67 88]
One line version: [82 91 67 88]


In [61]:
# Combining more than one condition needs & (and) / | (or), with each
# condition wrapped in its own brackets.
print("Scores between 50 and 90:", scores[(scores >= 50) & (scores <= 90)])
print("Scores below 40 OR above 85:", scores[(scores < 40) | (scores > 85)])

Scores between 50 and 90: [82 67 88]
Scores below 40 OR above 85: [91 34 88 20]


### `np.where()` — choosing values based on a condition, or finding positions

`np.where()` has two common jobs:

1. **Conditional replacement:** "if this condition is true, use this
   value, otherwise use that other value" — for every item in the array,
   all at once.
2. **Finding positions:** if you call it with ONLY a condition (no
   replacement values), it tells you the positions where that condition
   is true.


In [62]:
temps = np.array([15, 22, 30, 18, 35, 10])

# Job 1: replace values based on a condition.
# "If the temperature is 25 or above, label it 'Hot', otherwise 'Cool'."
labels = np.where(temps >= 25, "Hot", "Cool")
print("Labels:", labels)

Labels: ['Cool' 'Cool' 'Hot' 'Cool' 'Hot' 'Cool']


In [63]:
# Job 2: find the POSITIONS where a condition is true (no replacement values given)
hot_day_positions = np.where(temps >= 25)
print("Positions where it was hot:", hot_day_positions)

# This is useful when you need the index, not just the value
print("Actual hot temperatures using those positions:", temps[hot_day_positions])

Positions where it was hot: (array([2, 4]),)
Actual hot temperatures using those positions: [30 35]


## 3. Structural and Shape Transformations

Sometimes the numbers themselves are correct, but they are arranged in
the wrong "shape" for what you need next — for example, a tool you are
using might expect a single row of numbers, but your data is currently
arranged as a table. This section is about rearranging numbers WITHOUT
changing what the numbers actually are.

### Reshaping — changing the arrangement of rows and columns

`.reshape()` takes the same numbers and rearranges them into a new
shape, as long as the total number of items stays the same. Think of it
like taking 12 eggs and repacking them from one long row into a box with
3 rows and 4 columns — same 12 eggs, different arrangement.


In [64]:
numbers = np.arange(1, 13)   # numbers from 1 to 12, in a single row
print("Original shape:", numbers.shape)
print(numbers)

Original shape: (12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [65]:
# Reshape the same 12 numbers into a 3-row, 4-column table
reshaped = numbers.reshape(3, 4)
print("Reshaped to (3, 4):\n", reshaped)

# Reshape the same 12 numbers into a 4-row, 3-column table instead
reshaped_again = numbers.reshape(4, 3)
print("\nReshaped to (4, 3):\n", reshaped_again)

Reshaped to (3, 4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped to (4, 3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [66]:
# You can use -1 for one dimension and let NumPy work it out automatically
auto_reshaped = numbers.reshape(2, -1)   # "2 rows, and figure out the columns yourself"
print("Reshaped to (2, -1):\n", auto_reshaped)

Reshaped to (2, -1):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### Flattening — turning a multi-dimensional array back into a single row

`.flatten()` and `.ravel()` both do the same basic job: they take an
array with multiple rows and columns and squash it down into a single
long row (1 dimension). The difference between them is a technical
memory detail: `.flatten()` always makes a brand new, separate copy of
the data, while `.ravel()` tries to reuse the original data without
copying it whenever possible (which makes `.ravel()` slightly faster).
For everyday use, both give you the same result.


In [67]:
table = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Original table:\n", table)
print("Flattened with .flatten():", table.flatten())
print("Flattened with .ravel():", table.ravel())

Original table:
 [[1 2 3]
 [4 5 6]]
Flattened with .flatten(): [1 2 3 4 5 6]
Flattened with .ravel(): [1 2 3 4 5 6]


### Transposing — swapping rows and columns

"Transposing" means flipping an array so that its rows become columns
and its columns become rows. Picture a table lying flat, and then
rotating it so that what used to run left-to-right now runs top-to-bottom.


In [68]:
grid = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Original shape:", grid.shape)
print(grid)

print("\nTransposed using .T:")
print(grid.T)
print("New shape:", grid.T.shape)

# np.transpose() does exactly the same thing as .T
print("\nTransposed using np.transpose():")
print(np.transpose(grid))

Original shape: (2, 3)
[[1 2 3]
 [4 5 6]]

Transposed using .T:
[[1 4]
 [2 5]
 [3 6]]
New shape: (3, 2)

Transposed using np.transpose():
[[1 4]
 [2 5]
 [3 6]]


### Combining arrays — joining separate arrays into one

- `np.concatenate()` — joins two or more arrays together along a chosen
  direction (axis). It is the general-purpose joining function.
- `np.vstack()` — short for "vertical stack". Joins arrays by stacking
  them on top of each other, like adding new rows.
- `np.hstack()` — short for "horizontal stack". Joins arrays side by
  side, like adding new columns.


In [69]:
row1 = np.array([1, 2, 3])
row2 = np.array([4, 5, 6])
row3 = np.array([7, 8, 9])
row4 = np.array([10, 11, 12])
row5 = np.array([13, 14, 15])

# Stacking them as new ROWS, one on top of the other
stacked_rows = np.vstack([row1, row2, row3, row4, row5])
print("np.vstack() result:\n", stacked_rows)

np.vstack() result:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [70]:
# Stacking them SIDE BY SIDE, extending the row instead of adding a new one
stacked_side_by_side = np.hstack([row1, row2, row3, row4, row5])
print("np.hstack() result:", stacked_side_by_side)

np.hstack() result: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [71]:
# np.concatenate() on two 2D tables, joining them as extra rows (axis=0)
table_a = np.array([[1, 2], [3, 4]])
table_b = np.array([[5, 6], [7, 8]])

joined_rows = np.concatenate([table_a, table_b], axis=0)   # axis=0 means "stack downward"
print("Joined as extra rows (axis=0):\n", joined_rows)

joined_columns = np.concatenate([table_a, table_b], axis=1)   # axis=1 means "stack sideways"
print("\nJoined as extra columns (axis=1):\n", joined_columns)

Joined as extra rows (axis=0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Joined as extra columns (axis=1):
 [[1 2 5 6]
 [3 4 7 8]]


### Splitting arrays — breaking one array into several smaller pieces

`np.split()` does the opposite of combining: it cuts one array into
several equal pieces. You tell it how many equal pieces you want.


In [72]:
numbers = np.arange(1, 9)   # 1 to 8
print("Original:", numbers)

# Split into 4 equal pieces
pieces = np.split(numbers, 4)
print("Split into 4 pieces:")
for piece in pieces:
    print(piece)

Original: [1 2 3 4 5 6 7 8]
Split into 4 pieces:
[1 2]
[3 4]
[5 6]
[7 8]


## 4. Mathematical Operations and Vectorization

### Why is NumPy fast? Vectorization, explained simply

Normally in Python, if you want to add 5 to every number in a list, you
would write a loop that goes through the list one item at a time. NumPy
lets you skip the loop completely: you just write `array + 5`, and NumPy
applies the addition to every single number at once, using fast code
written in C behind the scenes. This trick — applying an operation to a
whole array at once instead of looping through it one item at a time —
is called **vectorization**, and it is the main reason NumPy is so much
faster than plain Python for number-crunching.

### Vectorized arithmetic — the basic building block


In [73]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("Addition (a + b):", a + b)
print("Subtraction (a - b):", a - b)
print("Multiplication (a * b):", a * b)   # multiplies matching positions together
print("Division (a / b):", a / b)

Addition (a + b): [11 22 33 44]
Subtraction (a - b): [ -9 -18 -27 -36]
Multiplication (a * b): [ 10  40  90 160]
Division (a / b): [0.1 0.1 0.1 0.1]


In [74]:
# You can also combine an array with a single plain number
prices = np.array([100, 200, 300])
discounted_prices = prices - 20   # subtract 20 from EVERY price at once
print("Prices after $20 discount:", discounted_prices)

Prices after $20 discount: [ 80 180 280]


### Broadcasting — doing maths between arrays of different shapes

"Broadcasting" is the rule NumPy uses to combine two arrays that are NOT
exactly the same shape. Instead of forcing you to make both arrays the
exact same size first, NumPy automatically "stretches" the smaller one
to match, as long as their shapes are compatible.

A simple way to picture it: imagine you have a table of prices for 3
products across 2 stores, and you want to apply the SAME 10% discount to
every single price. Instead of building a whole table full of 0.9s,
NumPy lets you just write `table * 0.9`, and it automatically applies
that single number to every cell in the table.


In [75]:
# A 2x3 table: 2 stores, 3 products
prices = np.array([
    [100, 200, 300],   # store 1
    [150, 250, 350]    # store 2
])

# A single number gets "broadcast" (stretched) across the whole table
discounted = prices * 0.9
print("After a flat 10% discount:\n", discounted)

After a flat 10% discount:
 [[ 90. 180. 270.]
 [135. 225. 315.]]


In [76]:
# Broadcasting also works between a table and a single row, as long as the
# number of columns matches. Here, each product has its own separate discount.
product_discounts = np.array([0.9, 0.8, 0.95])   # discount per PRODUCT (per column)

discounted_per_product = prices * product_discounts
print("Prices shape:", prices.shape)
print("Discounts shape:", product_discounts.shape)
print("Result after broadcasting:\n", discounted_per_product)

Prices shape: (2, 3)
Discounts shape: (3,)
Result after broadcasting:
 [[ 90.  160.  285. ]
 [135.  200.  332.5]]


**The basic broadcasting rule, in simple words:** NumPy compares the
shapes of the two arrays starting from the right-hand side. Two sizes are
considered compatible if they are exactly equal, OR if one of them is 1
(a size of 1 can always be stretched to match). If neither of those is
true, NumPy will raise an error, because it does not know how to line the
numbers up.


In [77]:
# An example of shapes that are NOT compatible, on purpose, to show the error
try:
    np.array([1, 2, 3]) + np.array([1, 2])
except ValueError as error:
    print("Broadcasting error:", error)

Broadcasting error: operands could not be broadcast together with shapes (3,) (2,) 


### Aggregate functions — turning many numbers into one summary number

An "aggregate" function takes a whole array and boils it down into a
single summary value (or one value per row/column). These are the same
kinds of summaries you would calculate for a set of exam scores.

- `np.sum()` — adds everything up.
- `np.mean()` — the average value.
- `np.median()` — the middle value once everything is sorted.
- `np.std()` — the "standard deviation", which measures how spread out
  the numbers are from the average. A small standard deviation means the
  numbers are all close together; a large one means they are spread far
  apart.


In [78]:
scores = np.array([60, 75, 80, 55, 90, 65, 100])

print("Sum:", np.sum(scores))
print("Mean (average):", np.mean(scores))
print("Median (middle value):", np.median(scores))
print("Standard deviation (spread):", np.std(scores))

Sum: 525
Mean (average): 75.0
Median (middle value): 75.0
Standard deviation (spread): 15.118578920369089


### The `axis` parameter — choosing rows vs columns for a summary

When you use an aggregate function on a 2D table, you can tell NumPy
whether to summarize ACROSS the rows or DOWN the columns, using the
`axis` parameter:

- `axis=0` — summarize DOWN each column (you get one answer per column).
- `axis=1` — summarize ACROSS each row (you get one answer per row).

A simple way to remember it: `axis=0` moves downward through the rows,
`axis=1` moves sideways through the columns.


In [79]:
# 3 students (rows), 2 subjects (columns): Math, Science
marks = np.array([
    [85, 90],
    [78, 88],
    [92, 95]
])

print("Total of all marks:", np.sum(marks))   # every value added together
print("Sum per SUBJECT (down each column, axis=0):", np.sum(marks, axis=0))
print("Sum per STUDENT (across each row, axis=1):", np.sum(marks, axis=1))
print("Average mark per subject (axis=0):", np.mean(marks, axis=0))

Total of all marks: 528
Sum per SUBJECT (down each column, axis=0): [255 273]
Sum per STUDENT (across each row, axis=1): [175 166 187]
Average mark per subject (axis=0): [85. 91.]


### Sorting and searching — ordering data and finding extreme values

- `np.sort()` — arranges the numbers in an array from smallest to
  largest, and gives you back a new sorted array.
- `np.argmax()` — does NOT give you the biggest value itself. It gives
  you the POSITION (index) where the biggest value is located. Think of
  "arg" as short for "argument", meaning "the position that produces
  this result".
- `np.argmin()` — the same idea, but for the smallest value's position.


In [80]:
scores = np.array([60, 95, 80, 55, 90])

print("Original:", scores)
print("Sorted:", np.sort(scores))

print("Position of the highest score:", np.argmax(scores))
print("The highest score itself:", scores[np.argmax(scores)])

print("Position of the lowest score:", np.argmin(scores))
print("The lowest score itself:", scores[np.argmin(scores)])

Original: [60 95 80 55 90]
Sorted: [55 60 80 90 95]
Position of the highest score: 1
The highest score itself: 95
Position of the lowest score: 3
The lowest score itself: 55


## 5. Advanced and Specialized Modules

### Linear algebra (`np.linalg`) — matrix maths, explained simply

A "matrix" is just another name for a 2-dimensional array (a table of
numbers). Linear algebra is the branch of maths that deals with matrices,
and NumPy has a dedicated toolbox for it called `np.linalg`.

- `np.dot()` and `@` — both perform "matrix multiplication", which is a
  specific way of combining two matrices together (it is NOT the same as
  multiplying matching positions one by one). `@` is simply a shorter,
  more modern way of writing the same operation as `np.dot()`.
- `np.matmul()` — does the same job as `np.dot()` for standard matrix
  multiplication; the two mainly differ in more unusual, higher-dimensional
  cases that beginners rarely run into.
- Determinant, inverse, and eigenvalues are three specific numbers/matrices
  that describe useful properties of a matrix, used heavily in solving
  systems of equations and in machine learning algorithms.


In [81]:
matrix_a = np.array([
    [1, 2],
    [3, 4]
])
matrix_b = np.array([
    [5, 6],
    [7, 8]
])

# Matrix multiplication - combining two matrices using the standard matrix rule
print("Using np.dot():\n", np.dot(matrix_a, matrix_b))
print("\nUsing @ (same result, shorter to write):\n", matrix_a @ matrix_b)
print("\nUsing np.matmul() (same result again):\n", np.matmul(matrix_a, matrix_b))

Using np.dot():
 [[19 22]
 [43 50]]

Using @ (same result, shorter to write):
 [[19 22]
 [43 50]]

Using np.matmul() (same result again):
 [[19 22]
 [43 50]]


In [82]:
# The determinant — a single number that describes certain properties of a matrix,
# such as whether it can be "inverted" (undone).
square_matrix = np.array([
    [4, 7],
    [2, 6]
])
determinant = np.linalg.det(square_matrix)
print("Determinant:", determinant)

# The inverse — a matrix that "undoes" the original matrix when multiplied together
# (similar to how dividing by a number undoes multiplying by that number).
inverse = np.linalg.inv(square_matrix)
print("Inverse:\n", inverse)

# Multiplying a matrix by its own inverse should give back the "identity matrix"
# (a matrix of 1s down the diagonal and 0s everywhere else) — this proves the inverse works.
print("Matrix multiplied by its inverse (should look like the identity matrix):\n",
      np.round(square_matrix @ inverse))

Determinant: 10.000000000000002
Inverse:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Matrix multiplied by its inverse (should look like the identity matrix):
 [[ 1. -0.]
 [ 0.  1.]]


In [83]:
# Eigenvalues and eigenvectors — special numbers and directions connected to a matrix,
# widely used in machine learning (for example, in techniques like PCA for reducing
# the number of features in a dataset).
eigenvalues, eigenvectors = np.linalg.eig(square_matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [1.12701665 8.87298335]
Eigenvectors:
 [[-0.92511345 -0.82071729]
 [ 0.37969079 -0.57133452]]


### Random sampling (`np.random`) — generating random numbers on purpose

NumPy has a whole toolbox for generating random numbers, which is useful
for testing code, simulating data, or shuffling a dataset.

- `np.random.rand()` — generates random decimal numbers between 0 and 1,
  where every value in that range is equally likely.
- `np.random.randint()` — generates random WHOLE numbers within a range
  you choose.
- `np.random.randn()` — generates random decimal numbers following a
  "normal distribution" (also called a bell curve), where numbers near 0
  are much more common than numbers far from 0, and the numbers can be
  negative or positive.
- Setting a random seed — computers cannot generate truly random numbers;
  they use a starting point called a "seed" to generate numbers that look
  random. If you set the seed to the same value every time, you will get
  the EXACT SAME "random" numbers every time you run the code. This is
  important for reproducibility, so that other people can run your code
  and get identical results.


In [84]:
# Setting a seed first, so this example always gives the same output
np.random.seed(42)

random_decimals = np.random.rand(5)          # 5 random decimals between 0 and 1
random_whole_numbers = np.random.randint(1, 100, size=5)   # 5 random whole numbers from 1 to 99
random_normal = np.random.randn(5)           # 5 random numbers from a bell-curve distribution

print("Random decimals (0 to 1):", random_decimals)
print("Random whole numbers (1 to 99):", random_whole_numbers)
print("Random bell-curve numbers:", random_normal)

Random decimals (0 to 1): [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Random whole numbers (1 to 99): [83 87 75 75 88]
Random bell-curve numbers: [-0.88523035 -0.41218848 -0.4826188   0.16416482  0.23309524]


In [85]:
# Proving that the seed makes the results repeatable
np.random.seed(42)
first_try = np.random.randint(1, 100, size=5)

np.random.seed(42)
second_try = np.random.randint(1, 100, size=5)

print("First try: ", first_try)
print("Second try:", second_try)
print("Are they identical?", np.array_equal(first_try, second_try))

First try:  [52 93 15 72 61]
Second try: [52 93 15 72 61]
Are they identical? True


### Handling missing data — `np.nan` and `np.inf`, explained simply

Real data is often incomplete or has unusual values. NumPy has two
special markers for this:

- `np.nan` — stands for "Not a Number". It represents a missing or
  undefined value, such as a sensor reading that failed to record, or a
  survey question someone left blank.
- `np.inf` — stands for "Infinity". It represents a value that is larger
  than any number can measure, which usually shows up as the result of
  dividing a number by zero.

An important quirk: `np.nan` is never considered equal to anything, not
even to another `np.nan`. This means you cannot check for it using a
normal `== ` comparison — you need a special function instead.


In [86]:
data = np.array([25.0, np.nan, 30.0, np.inf, 18.0, np.nan])
print("Data:", data)

# This is the WRONG way to check for missing values - it will not work correctly
print("Wrong way (using == np.nan):", data == np.nan)

# This is the CORRECT way to detect missing values
print("Correct way (using np.isnan()):", np.isnan(data))

# Detecting infinite values
print("Detecting infinity (using np.isinf()):", np.isinf(data))

Data: [25. nan 30. inf 18. nan]
Wrong way (using == np.nan): [False False False False False False]
Correct way (using np.isnan()): [False  True False False False  True]
Detecting infinity (using np.isinf()): [False False False  True False False]


In [87]:
# A common real-world step: replacing missing values with a chosen number,
# such as the average of all the valid (non-missing) numbers.
valid_values = data[~np.isnan(data) & ~np.isinf(data)]   # keep only normal numbers
average_value = np.mean(valid_values)
print("Average of the valid numbers only:", average_value)

# np.nan_to_num() replaces NaN and infinite values with normal numbers in one step
cleaned_data = np.nan_to_num(data, nan=average_value, posinf=999, neginf=-999)
print("Cleaned data:", cleaned_data)

Average of the valid numbers only: 24.333333333333332
Cleaned data: [ 25.          24.33333333  30.         999.          18.
  24.33333333]


## 6. Performance Optimization

### Vectorization vs. loops — proving that vectorization is faster

We already explained WHY vectorization is fast in Section 4. Here, we
prove it by actually timing both approaches on the same task: adding two
large lists of numbers together, once using a plain Python loop, and once
using NumPy's vectorized addition.


In [88]:
import time

size = 1_000_000
list_a = list(range(size))
list_b = list(range(size))

array_a = np.array(list_a)
array_b = np.array(list_b)

# Method 1: a plain Python loop, one item at a time
start_time = time.time()
result_loop = [list_a[i] + list_b[i] for i in range(size)]
loop_time = time.time() - start_time

# Method 2: NumPy vectorized addition, the whole array at once
start_time = time.time()
result_vectorized = array_a + array_b
vectorized_time = time.time() - start_time

print(f"Python loop time:      {loop_time:.4f} seconds")
print(f"NumPy vectorized time: {vectorized_time:.4f} seconds")
print(f"NumPy was about {loop_time / vectorized_time:.0f} times faster")

Python loop time:      0.0828 seconds
NumPy vectorized time: 0.0020 seconds
NumPy was about 41 times faster


### Views vs. copies — a trap that catches almost every beginner

This is one of the most important ideas to understand properly, because
getting it wrong can silently corrupt your data without any error message.

- A **view** is a new array that LOOKS like a separate array, but is
  secretly still pointing at the same underlying data as the original.
  If you change a value in the view, the original array changes too,
  because they are really sharing the same memory.
- A **copy** is a completely independent, brand new array with its own
  separate memory. Changing the copy does NOT affect the original at all.

**The rule to remember:** basic slicing (using a `:` to select a range)
usually creates a VIEW. Fancy indexing (using a list of positions) and
boolean masking usually create a COPY. When in doubt, and you need to be
certain you are working with an independent array, call `.copy()`
explicitly.


In [89]:
original = np.array([10, 20, 30, 40, 50])

# Basic slicing -> this creates a VIEW, not an independent copy
sliced_view = original[1:4]
print("Sliced view:", sliced_view)

sliced_view[0] = 999   # changing the view...
print("Sliced view after change:", sliced_view)
print("Original array also changed!:", original)   # ...changed the original too!

Sliced view: [20 30 40]
Sliced view after change: [999  30  40]
Original array also changed!: [ 10 999  30  40  50]


In [90]:
# Now let's do the same thing, but using .copy() to break the connection on purpose
original = np.array([10, 20, 30, 40, 50])

safe_copy = original[1:4].copy()   # .copy() forces a truly independent array
safe_copy[0] = 999

print("Safe copy after change:", safe_copy)
print("Original array is unaffected:", original)

Safe copy after change: [999  30  40]
Original array is unaffected: [10 20 30 40 50]


In [91]:
# Fancy indexing (a list of positions) behaves differently - it returns a COPY automatically
original = np.array([10, 20, 30, 40, 50])

fancy_result = original[[1, 2, 3]]   # a list of positions -> this is fancy indexing
fancy_result[0] = 999

print("Fancy indexing result after change:", fancy_result)
print("Original array is unaffected:", original)

Fancy indexing result after change: [999  30  40]
Original array is unaffected: [10 20 30 40 50]


In [92]:
# You can always check whether an array is a view or owns its own data
# using the .base attribute: if .base is None, the array owns its data (it's independent).
# If .base is NOT None, it is a view into another array.
original = np.array([1, 2, 3, 4, 5])
a_view = original[1:3]
a_copy = original[1:3].copy()

print("Does the view share memory with original?", a_view.base is original)
print("Does the copy share memory with original?", a_copy.base is original)

Does the view share memory with original? True
Does the copy share memory with original? False


## 7. Quick Reference Cheat-Sheet

| What you want to do | How to do it |
|---|---|
| Create an array from a list | `np.array([1, 2, 3])` |
| Create an array of all zeros | `np.zeros((rows, cols))` |
| Create an array of all ones | `np.ones((rows, cols))` |
| Count up in steps | `np.arange(start, stop, step)` |
| Get an exact number of evenly spaced values | `np.linspace(start, stop, how_many)` |
| Check the shape (rows, columns) | `array.shape` |
| Check how many dimensions | `array.ndim` |
| Check the total number of items | `array.size` |
| Check what type of numbers are stored | `array.dtype` |
| Convert to a different data type | `array.astype(new_type)` |
| Pick one item | `array[position]` or `array[row, col]` |
| Pick a range of items | `array[start:stop]` |
| Pick scattered items | `array[[pos1, pos2, pos3]]` |
| Filter using a condition | `array[array > value]` |
| Replace values based on a condition | `np.where(condition, value_if_true, value_if_false)` |
| Change the shape without changing the data | `array.reshape(rows, cols)` |
| Flatten to a single row | `array.flatten()` or `array.ravel()` |
| Swap rows and columns | `array.T` or `np.transpose(array)` |
| Stack arrays as new rows | `np.vstack([array1, array2])` |
| Stack arrays side by side | `np.hstack([array1, array2])` |
| General joining of arrays | `np.concatenate([array1, array2], axis=...)` |
| Break an array into equal pieces | `np.split(array, how_many_pieces)` |
| Add/subtract/multiply/divide element by element | `+`, `-`, `*`, `/` |
| Add up all the numbers | `np.sum(array)` |
| Find the average | `np.mean(array)` |
| Find the middle value | `np.median(array)` |
| Find how spread out the numbers are | `np.std(array)` |
| Sort from smallest to largest | `np.sort(array)` |
| Find the position of the biggest value | `np.argmax(array)` |
| Find the position of the smallest value | `np.argmin(array)` |
| Multiply two matrices together | `matrix_a @ matrix_b` or `np.dot(matrix_a, matrix_b)` |
| Find the determinant of a matrix | `np.linalg.det(matrix)` |
| Find the inverse of a matrix | `np.linalg.inv(matrix)` |
| Generate random decimals (0 to 1) | `np.random.rand(size)` |
| Generate random whole numbers | `np.random.randint(low, high, size)` |
| Generate bell-curve random numbers | `np.random.randn(size)` |
| Make random numbers repeatable | `np.random.seed(number)` |
| Check for missing values | `np.isnan(array)` |
| Check for infinite values | `np.isinf(array)` |
| Replace missing/infinite values | `np.nan_to_num(array, nan=..., posinf=..., neginf=...)` |
| Force an independent copy (not a view) | `array.copy()` |

---

### A short closing note

The biggest habit to build from this notebook is this: whenever you catch
yourself writing a `for` loop to go through a NumPy array one item at a
time, stop and ask whether a vectorized operation, a boolean mask, or an
aggregate function could do the same job in one line, without the loop.
That single habit is responsible for most of the speed advantage NumPy
gives you over plain Python.
